server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/data_analystic"
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.dto
  configuration:
    map-underscore-to-camel-case: true

servlet:
  multipart:
    enabled: true
    max-file-size: 20MB        # gi?i h?n kích th??c file upload
    max-request-size: 20MB     # gi?i h?n request bao g?m file
    file-size-threshold: 2KB


